### ISSUE TITLE
compile error

### ISSUE THREAD

**Issue by BernhardOnline** [pasis/pppoat2#1]
I can't compile pppoat2.   ./autogen ran without any trouble/notice, but  then

./configure 
checking for a BSD-compatible install... /usr/bin/install -c
checking whether build environment is sane... yes
checking for a thread-safe mkdir -p... /bin/mkdir -p
checking for gawk... gawk
checking whether make sets $(MAKE)... yes
checking whether make supports nested variables... yes
checking for gcc... gcc
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables... 
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether gcc accepts -g... yes
checking for gcc option to accept ISO C89... none needed
checking whether gcc understands -c and -o together... yes
checking whether make supports the include directive... yes (GNU style)
checking dependency style of gcc... gcc3
./configure: line 3447: syntax error near unexpected token `,'
./configure: line 3447: `AX_PTHREAD(, AC_MSG_ERROR([pthreads not found!]))'
root@debian-10:~/pppoat2# 

despite having all libraries containing *pthread* in debian-10 installed:

find /lib/ -iname \*pthread*

/lib/x86_64-linux-gnu/libpthread-2.28.so
/lib/x86_64-linux-gnu/libpthread.so.0

no clue how to proceed. Any hints? Cheers

**Comment by pasis** [comment]
Please check that you have installed `autoconf-archive`.
